" All loaded vim bundles through NeoBundle
source $HOME/.vim/bundles.vim

" Navigation vim configurations
source $HOME/.vim/typing.vim

" General vim configurations
source $HOME/.vim/general.vim

" Interface vim configurations
source $HOME/.vim/interface.vim

" Navigation vim configurations
source $HOME/.vim/navigation.vim

" Shortcuts vim configurations
source $HOME/.vim/shortcuts.vim
